### ISSUE TITLE
Error Leading digit

### ISSUE THREAD

**Issue by dzhenway** [duo-labs/secret-bridge#1]
Hi,

I love this tool, but when i tried
i got this error

~/tools/secret-bridge$ python3 main.py webhook
This float doesn't have a leading digit (line 10 column 1 char 133)

i set up my github token, slack webhook and  monitor organizatition like this

detectors = [
    "detect-secrets",
    "git-secrets"
]

[auth]
access_token='13246567878'

[monitors]
    organizations = [org1,org2,org3,org4,org5]$    
    users = []
    repos = []

[webhook]
    secret=""
    host="0.0.0.0"

[notifiers.console]

[notifiers.slack_webhook]
    webhook_url='https://hooks.slack.com/services/xxxx/xxxxx/xxxxxxxJ'

thank you

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. Out of curiosity, is the `$` actually in your YAML file next to the `organizations` key? If so, that might be a typo which can be removed.

**Comment by jordan-wright** [comment]
Also, you might consider adding quotes around your organization names. Looking through the [toml documentation for that error](https://github.com/uiri/toml/blob/deb0365887be610664fe48ef69c214f6119e576a/toml/decoder.py#L876) suggests that if the value starts with a `.`, `e`, or `E`, it will try to convert it to a float. My guess is that you have an organization name that starts with an e and isn't being quoted.

I hope this helps!

**Comment by jordan-wright** [comment]
Going ahead and closing this since there haven't been any updates in a few days. @dzhenway if you're still running into issues, let me know and we can continue troubleshooting.

Thanks for getting in touch!
