### ISSUE TITLE
Trufflehog support for webhook

### ISSUE THREAD

**Issue by Rajshr** [duo-labs/secret-bridge#10]
Hi,

Is the webhook functionality supported for trufflehog?
Can someone provide some insight into it?

Thanks.

**Comment by nickmooney** [comment]
Hi @Rajshr,

The webhook functionality in `secret-bridge` is used to ingest data into `secret-bridge`, where it will then be distributed to the configured detectors. truffleHog is one of the supported detectors, so there shouldn't be a need for any special support if you're using webhooks.

Are there any particular issues you're running into?

**Comment by Rajshr** [comment]
Hi @nickmooney ,
My assumption is that once the'secret-bridge''application is up and running the webhook would be created for the mentioned repos in config.toml

Let me know if it is otherwise as the webhook is not being created.

Thanks

**Comment by jordan-wright** [comment]
Hey @Rajshr,

You're correct that if you specify the `webhook` configuration options (make sure to include a secret!) and run `secret-bridge` using the `webhook` command, then the webhook will start. You should see output similar to this:

```
INFO:root:Starting webhook server at /webhook
 * Serving Flask app "commands.webhook.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

If this isn't what you see, please post the relevant parts of your configuration and both the command and associated output you see when you run secret-bridge.

**Comment by Rajshr** [comment]
Hey @jordan-wright ,

I have below configuration in config.toml

detectors = [
    "detect-secrets",
    "git-secrets",
    "trufflehog"
]

[auth]
access_token='my_access_token'

[monitors]
    organizations = ["my_org"]
    users = ["user"]
    repos = ["test"]

[webhook]
    secret="test"
    host="0.0.0.0"

[notifiers.console]

[notifiers.slack_webhook]
    webhook_url=''


The command used is ` python main.py -f config.toml webhook`

and output is
```
INFO:root:Setting up detector: detect-secrets
INFO:root:Setting up detector: git-secrets
INFO:root:Setting up detector: trufflehog
INFO:root:Setting up notifier: console
INFO:root:Setting up notifier: slack_webhook
INFO:root:Starting webhook server at /webhook
 * Serving Flask app "commands.webhook.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

I don't see any webhook getting added for the repo mentioned in configuration nor do I see any message in console once I push the secrets/password to the repo.

can you provide some more insight on it,

Thanks.

**Comment by jordan-wright** [comment]
Ah, I see the issue. So secret bridge doesn’t use GitHub’s API to automatically add the webhook to your repository. Rather, it creates a webhook server (you can see Flask running) that receives webhook events which kicks off secret scanning tools.

You will need to configure a webhook in your repository that points to your secret bridge server.

**Comment by Rajshr** [comment]
@jordan-wright ,
Thanks for your response.So what the payload URL for the GitHub repo would be 'http://(HOSTNAME):5000/webhook ??

Any other configuration needed apart from payload URL

**Comment by jordan-wright** [comment]
Yep! That's correct. You'll just need to make sure that GitHub can reach the URL you provide, and that the secrets match up.

**Comment by jordan-wright** [comment]
Since the original issue appears to be solved, I'm going to go ahead and close this one out. @Rajshr please do let me know if you continue to run into issues using secret-bridge!
